source 'https://rubygems.org'

gem 'rake'
gem 'ruby_motion_query', github: 'infinitered/rmq'
gem 'motion-support'
gem 'bubble-wrap'
gem 'cocoapods-core'
gem "motion-cocoapods"

# Add your dependencies here:
