# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

require 'bubble-wrap/mail'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'lrm'
  #app.frameworks += ['MessageUI']

  app.pods do
    pod 'SVProgressHUD'
  end

end
